### ISSUE TITLE
MP's for NCR, reinforcements.

### ISSUE THREAD

**Issue by Cpkeyes** [Drymouth-Gulch/Drymouth-Gulch#100]
To help the captain enforce his or her orders and help keep the troopers in line. MP's should be a role that players can play. They can be in charge of both guarding the base and ensuring no legion or raiders enter, and enforcing the law amongst the trooper.

They can e simply equipped with basic armor, a stun baton and pistol. But have access to better equipment if a riot or assault breaks out.

I'm not sure if this other idea would work, but the Captain should be able to call in reinforcements via the radio, perhaps spawning in new troopers, rangers or even heavy troopers.

**Comment by Angryon** [comment]
![GitHub Logo](https://image.prntscr.com/image/85gSg3bBRY6c_YLmEiCzUQ.png)
