### ISSUE TITLE
No way to make 40-70 gvt ammo or a reliable way to get 40-70 gvt ammo

### ISSUE THREAD

**Issue by awesine** [Drymouth-Gulch/Drymouth-Gulch#105]
No 40-70 GVT spawns reliably on the map nor can you make any.

**Comment by Angryon** [comment]
If you need more of the 70 damage per round bullets, you either didn't need them or didn't deserve to have them.

You've got 18 of them, and unless you're fighting a horde of Centurions, you probably shouldn't need more.
