### ISSUE TITLE
Stimpacks

### ISSUE THREAD

**Issue by ishitbyabullet** [Drymouth-Gulch/Drymouth-Gulch#107]
A syringe rifle and two stimpacks sometimes spawns in some spots. These stimpacks are different from stimpaks, though. A stimpack gives stimulants. . I'm sure you can figure out why that is bad. A stimpak heals.

I saw 5 syringe rifles in one building. This should probably be fixed or we need an admin who can mass delete.

**Comment by Angryon** [comment]
do you remember what building it was? the syringer rifle should be a tier5 spawn

**Comment by ishitbyabullet** [comment]
@Angryon Clinic. The fucking clinic.

**Comment by Angryon** [comment]
#106 should have fixed this.
