### ISSUE TITLE
Fix the Brotherhood Bunker's atmos problems

### ISSUE THREAD

**Issue by Nick123q23** [Drymouth-Gulch/Drymouth-Gulch#147]
Atmos in the rear part of the bunker, like the R&D lab, Hydroponics, hidden room and generator room, is fucked and causes people to die when exposed to these areas for prolonged periods of time

**Comment by LR001** [comment]
i'm just going to re-design the bunker when I have the time.. not gonna be fucked to deal with whatever code snipet in some random hidden spot broke the atmosphere in that little section..

**Comment by LR001** [comment]
Fixed in #151
