### ISSUE TITLE
Power Storage Unit Blocking Generator

### ISSUE THREAD

**Issue by KKarmac** [Drymouth-Gulch/Drymouth-Gulch#27]
https://i.gyazo.com/90ca7f2e59d2035850741407b0cb1531.png

As you can see in the image, you can't actually get to the APC or the PACMAN Generator and it's not hooked up to the NCR power plant so once that thing runs out of juice your fucked unless you got tools to rebuild the power unit somewhere else. So if you guys could move it around a bit I'd really appreciate that.

The location is the small house to the south-east corner of the map.

**Comment by namjay1170** [comment]
Fixed.
