### ISSUE TITLE
Suggestion: Make the grease gun fire 9mm and add a .45 auto smg in the form of the Thompson machine gun

### ISSUE THREAD

**Issue by mike317** [Drymouth-Gulch/Drymouth-Gulch#36]
despite the grease gun canonically shooting 45 before nv, making it shoot 9mm would give variety to the guns that use this caliber and there would still be something to fill the slot for the .45 smg.

**Comment by namjay1170** [comment]
The Tommy gun already exists and uses .45, its currently a tier 5 spawn do to it being a powerful gun.
