### ISSUE TITLE
Addtional Clothing Sprites

### ISSUE THREAD

**Issue by KKarmac** [Drymouth-Gulch/Drymouth-Gulch#42]
Headwraps and Handwraps so I can look like this guy would be neat,

http://2.bp.blogspot.com/-j1rUbDWWZ8k/UcLQPQdE1PI/AAAAAAAAEJs/b7NbKC83sUM/s1600/joshua_graham.jpg

bonus points if you redo the bulletproof vest to be a SWAT vest and make it look like the one in the image.

**Comment by namjay1170** [comment]
Remake this on the paragulch
