### ISSUE TITLE
Fix Bandoliers

### ISSUE THREAD

**Issue by KKarmac** [Drymouth-Gulch/Drymouth-Gulch#43]
Currently they can only contain enough ammo for one full reload of a hunting shotgun, making them relatively useless, if they were capable of holding three rows of shotgun shells, and spawned anywhere other than the secret farm in the middle of nowhere, that'd be nice.

**Comment by CameronWoof** [comment]
See https://github.com/Drymouth-Gulch/Drymouth-Gulch/pull/76 for possible implementation.

**Comment by ma44** [comment]
Fixed by https://github.com/Drymouth-Gulch/Drymouth-Gulch/pull/76
