### ISSUE TITLE
Lower the speed of Protectron units

### ISSUE THREAD

**Issue by KKarmac** [Drymouth-Gulch/Drymouth-Gulch#44]
With any luck this'll make it easier for people to not die to them, or aggro them onto the city streets and ruin the lives of others. And if you're lagging or hit by a single laser it's usually enough of a slowdown for the protectron to run up to you and bash you a couple times, which does painfully large amounts of damage.

**Comment by namjay1170** [comment]
They are already twice as slow as they were previously. and damaged nerfed.

**Comment by KKarmac** [comment]
fffffffffffffffffffffffffffffffffffffffffffffffffffffffucking

robits

**Comment by namjay1170** [comment]
done
