### ISSUE TITLE
Resprite the SWAT helmet

### ISSUE THREAD

**Issue by KKarmac** [Drymouth-Gulch/Drymouth-Gulch#45]
Changing it from the strange Black and Red Stripes with Blue Visor sprite to something more like;

http://i.ebayimg.com/00/s/MTAwMFgxMDAw/z/ChwAAMXQDfdRv~VA/$(KGrHqYOKosFG8zBJY,DBRv+V!BBWQ~~60_3.JPG (Goggles included in the helmet sprite would be very niceu)

or

http://motorclothes.harley-davidson.eu/images/products/EC_98318_15E_F_T.jpg

Would be super awesome, even if it does basically just look like a black combat helmet, it'll be infinitely better than what we've got right now.

**Comment by namjay1170** [comment]
done
