### ISSUE TITLE
New Chem - Fixer

### ISSUE THREAD

**Issue by KKarmac** [Drymouth-Gulch/Drymouth-Gulch#46]
If there isn't already a chem that removes addictions, being able to create one would be nice, something like a mix of charcoal and mannitol would make sene, even if you hold this off till we move to paragulch it'd be nice to see implemented.

**Comment by Angryon** [comment]
[There you go.](https://github.com/Drymouth-Gulch/Drymouth-Gulch/pull/47)

**Comment by KKarmac** [comment]
god bless

**Comment by AndrewL97** [comment]
YAY
