### ISSUE TITLE
Brotherhood of Steel APC is non-existant

### ISSUE THREAD

**Issue by Coroneljones** [Drymouth-Gulch/Drymouth-Gulch#50]
The BoS base has no APC, atleast visible, and you cant build a new one since the area belives an APC is already there.

Furthermore, if its there, its not connected to the SMES and generator

Update: Did some checking, the whole SOB base is marked as "Upper Enclave Base" or something along those lines, might explain the inability to build an APC

**Comment by KKarmac** [comment]
Pretty sure this is already a confirmed issue, Ren's told people this when they complain about it on the discord, hopefully a fix is coming soon

**Comment by AndrewL97** [comment]
map is very weird and bugtastic atm, is being totally rejigged for para. no fix till then very likely

**Comment by namjay1170** [comment]
The APC is located in the Enclave base do to NCR simply disabling it when it was in the powerplant, their is an issue that an admin has to cycle the apc to get it working.
