### ISSUE TITLE
Not enough caps

### ISSUE THREAD

**Issue by turnop** [Drymouth-Gulch/Drymouth-Gulch#56]
The absolutely tiny amount of caps that you spawn with (0-4) means that you get two kinds of people: those who either have no or almost no currency and a small handful who've hit the den first and have 100+ caps. This makes running a shop extremely difficult, as the prices you have to set to make sales must be modulated enormously, and you have to determine the price you can charge to actually make a sale without causing your customer to immediately leave based on no discernible factors. Giving people a reasonable amount of caps at spawn would make a consistent economy possible, where freshly-spawned people are able to buy things just as well as those who hit the den quickly.

**Comment by Angryon** [comment]
something something caps have no use something something debases the economy
