### ISSUE TITLE
Add first-aid kits to the crafting menu for cardboard sheets

### ISSUE THREAD

**Issue by CameronWoof** [Drymouth-Gulch/Drymouth-Gulch#61]
Producing chems is currently pretty easy, but distributing them requires hand labeling boxes or putting them in ammo cases and weird stuff like that. Being able to turn generic boxes into first-aid kits will allow people to actually package medicine in a visible way.

**Comment by namjay1170** [comment]
the next question is, would the first aid kit be able to be made into cardboard

**Comment by CameronWoof** [comment]
See https://github.com/Drymouth-Gulch/Drymouth-Gulch/pull/75 for implementation.
