### ISSUE TITLE
Allow armor kits to be craftable and applied to suit-slot items to grant them an armor value

### ISSUE THREAD

**Issue by CameronWoof** [Drymouth-Gulch/Drymouth-Gulch#62]
Mostly for dolly dressup. Doesn't have to, and would be preferred not to, actually alter the sprite.

**Comment by Angryon** [comment]
note to self to do this thing

**Comment by LR001** [comment]
added in craftable armor kits in#135 will look into suit slot items.

**Comment by AndrewL97** [comment]
@LR001 This is what I meant about making kits a sub of goliath plates that affect the under clothing

**Comment by LR001** [comment]
@AndrewL97 i'll see if i can do it. i was thinking about making goliath plates their own just remodeled and renamed to kevlar plates and have the ability to attach to an under.

**Comment by LR001** [comment]
Completed in #151
