### ISSUE TITLE
Prototype AER14 laser rifle beams stuck on chain fence

### ISSUE THREAD

**Issue by GelatinousGlob** [Drymouth-Gulch/Drymouth-Gulch#69]
Shoot the prototype AER14 xray laser rifle at a chain link fence, beam gets stuck on the fence and jiggles in place.

**Comment by LR001** [comment]
Attempted to recreate the bug and couldn't.. Was there anything else that was going on around you that you believe could be relevant?

**Comment by LR001** [comment]
I couldn't get the bug to replicate and since the author has not responded, I'm going to be closing this issue...
