### ISSUE TITLE
Add Wooden Planks to the Legion Camp's Storage Hut

### ISSUE THREAD

**Issue by CameronWoof** [Drymouth-Gulch/Drymouth-Gulch#80]
Often used to make extra tables or crosses; very useful, could use some without having to deconstruct a few houses in the Den.

**Comment by namjay1170** [comment]
Many wooden tree's exist and can be cut down for wood, but yes, they need more round start materials.

**Comment by LR001** [comment]
This can be closed as it was added in #102
