### ISSUE TITLE
Frames go to bad decline

### ISSUE THREAD

**Issue by Dragoon458** [Drymouth-Gulch/Drymouth-Gulch#99]
Whenever I go to Sunnydale in certain parts, including the clinic, my frames decline to a putter for some odd reason quite quickly.

**Comment by Angryon** [comment]
have we actually figured out if anyone else has this problem yet

**Comment by AndrewL97** [comment]
Still waiting on other reports for this issue - Ill close this at 30 days old if still nobody else
Or unless Dragoon can give us more details

**Comment by LR001** [comment]
It appears you are the only one with this issue that has come forward. .. If you can give us any more details please place it in the dev chat..
